services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    ports:
      - "4822:4822"
    restart: unless-stopped
  test-ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: test-ssh
    environment:
      - TZ=Europe/Warsaw
      - USER_NAME=labuser
      - USER_PASSWORD=labpass
      - PASSWORD_ACCESS=true
    ports:
      - "2222:2222"
    restart: unless-stopped
  test-vnc:
    image: accetto/ubuntu-vnc-xfce-g3:latest
    container_name: test-vnc
    environment:
      - VNC_PW=labpass
      - VNC_RESOLUTION=1920x1080
    ports:
      - "5901:5901" # Dla Guacamole (Natywne VNC)
      - "6901:6901" # Opcjonalnie: bezpośrednio w przeglądarce (noVNC)
    restart: unless-stopped
  test-rdp:
    image: scottyhardy/docker-remote-desktop:latest
    container_name: test-rdp
    ports:
      - "3389:3389"
    restart: unless-stopped
    #login ubuntu
    #hasło ubuntu
