services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rl_backend
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - GUACD_HOST=guacd
      - DEBUG=False
      # - ALLOWED_HOSTS=twoja_domena.com,localhost
    depends_on:
      - redis
      - guacd

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rl_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: rl_redis
    restart: unless-stopped

  guacd:
    image: guacamole/guacd:1.5.5
    container_name: rl_guacd
    restart: unless-stopped
