# Generated by Django 5.2.16 on 2026-07-30 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('protocol', models.CharField(choices=[('vnc', 'VNC'), ('rdp', 'RDP'), ('ssh', 'SSH')], default='vnc', max_length=8)),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('width', models.PositiveIntegerField(default=1024)),
                ('height', models.PositiveIntegerField(default=768)),
                ('dpi', models.PositiveIntegerField(default=96)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
