# Generated by Django 5.2.16 on 2026-08-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0002_machine_delete_remotesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, unique=True)),
                ('protocol', models.CharField(default='REST_JSON', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
