# Generated by Django 5.2.16 on 2026-08-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0003_pdu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDUOutletMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdu_ip', models.CharField(max_length=50)),
                ('outlet_id', models.IntegerField()),
                ('custom_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('pdu_ip', 'outlet_id')},
            },
        ),
    ]
