# Generated by Django 5.2.16 on 2026-08-21 10:07

import remote.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0004_pduoutletmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='credentials',
            field=remote.models.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
